# name: CD

# on:
#   push:
#     branches:
#       - main
#       - master

# jobs:
#   start:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dummy job to start CD workflow
#         run: echo "Starting CD workflow"

#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Azure Container Registry
#         uses: azure/docker-login@v1
#         with:
#           login-server: ${{ secrets.ACR_LOGIN_SERVER }}
#           username: ${{ secrets.ACR_USERNAME }}
#           password: ${{ secrets.ACR_PASSWORD }}

#       - name: Build Docker image
#         run: |
#           docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/progress-bar-app .
#           docker push ${{ secrets.ACR_LOGIN_SERVER }}/progress-bar-app

#       - name: Azure AKS Login
#         run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

#       - name: Azure AKS Get Credentials
#         run: az aks get-credentials --resource-group company --name progressBar-aks-cluster

#       - name: Apply Kubernetes manifests
#         run: kubectl apply -f k8s/deployment.yml

#       - name: Apply Kubernetes service manifest
#         run: kubectl apply -f k8s/service.yml
