name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: npm install

      - name: Build js application
        run: npm run build
